# NOTE: update this with your service name
service: hootify-linkedin-crawl-dev
useDotenv: true
# Create an optimized package for our functions
package:
  individually: true
  exclude:
    - node_modules/puppeteer/.local-chromium/**

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-chrome
provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-1

functions:
  signUp:
    handler: src/handlers/linkedin.crawlProfile
    events:
      - http:
          path: /${self:provider.stage}/linkedin-crawel
          method: GET
