# NOTE: update this with your service name
service: hootify-linkedin-crawl-dev
useDotenv: true
# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables


provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-1

functions:
  signUp:
    handler: src/handlers/linkedin.ProfileCrawler
    events:
      - httpApi:
          path: /${self:provider.stage}/linkedin-crawel
          method: GET
